# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/manak_desktop_app.py'],
    pathex=['.', 'src', 'src/processors', 'src/license', 'src/utils'],
    binaries=[
        ('drivers/chromedriver.exe', '.'),
    ],
    datas=[
        ('config', 'app_config'),
        ('src/config.py', '.'),
        ('fonts', 'fonts'),
        ('resources', 'resources'),
        ('src/processors', 'src/processors'),
        ('src/license', 'src/license'),
        ('src/utils', 'src/utils'),
    ],
    hiddenimports=[
        'config',
        'pandas',
        'pandas.io.formats.excel',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions',
        'requests',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'mysql.connector',
        'mysql.connector.locales',
        'mysql.connector.locales.eng',
        'mysql.connector.plugins',
        'mysql.connector.plugins.mysql_native_password',
        'mysql.connector.plugins.caching_sha2_password',
        'mysql.connector.cursor',
        'mysql.connector.pooling',
        'mysql.connector.errors',
        'openpyxl',
        'xlrd',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        # Processor modules (both src.processors and processors paths)
        'processors',
        'processors.bill_import_processor',
        'processors.completed_jobs_scanner',
        'processors.delivery_voucher_scanner',
        'processors.delivery_voucher_processor',
        'processors.job_cards_processor',
        'processors.multiple_jobs_processor',
        'processors.weight_capture_processor',
        'processors.bulk_jobs_report_submit',
        'processors.huid_data_processor',
        'processors.request_generator',
        'processors.simple_embedded_browser',
        'processors.simple_job_creator',
        'processors.jeweller_request_generator',
        'processors.job_card_exporter',
        'src.processors',
        'src.processors.bill_import_processor',
        'src.processors.completed_jobs_scanner',
        'src.processors.delivery_voucher_scanner',
        'src.processors.delivery_voucher_processor',
        'src.processors.job_cards_processor',
        'src.processors.multiple_jobs_processor',
        'src.processors.weight_capture_processor',
        'src.processors.bulk_jobs_report_submit',
        'src.processors.huid_data_processor',
        'src.processors.request_generator',
        'src.processors.simple_embedded_browser',
        'src.processors.simple_job_creator',
        'src.processors.jeweller_request_generator',
        'src.processors.job_card_exporter',
        'src.license',
        'src.license.device_license',
        'src.utils',
        'license',
        'license.device_license',
        'utils',
        'utils.font_loader',
        'utils.tag_manager',
        'portal_config',
        'threading',
        'time',
        'datetime',
        'random',
        'json',
        'os',
        'sys',
        'sqlite3',
        'logging',
        'traceback',
        'hashlib',
        'uuid',
        'base64',
        'subprocess',
    ],
    hookspath=['.'],  # Use hooks from current directory
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Single-file EXE
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='manak_desktop_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # Disable UPX for better Windows 7 compatibility
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

# Folder-based portable distribution
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='manak_desktop_app_portable',
)
