# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['manak_desktop_app.py'],
    pathex=[],
    binaries=[
        ('chromedriver.exe', '.'),
    ],
    datas=[
        ('config', 'config'),
        ('device_license.py', '.'),
        ('multiple_jobs_processor.py', '.'),
        ('huid_data_processor.py', '.'),
        ('request_generator.py', '.'),
        ('submit_huid_data_api.php', '.'),
    ],
    hiddenimports=[
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions',
        'requests',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'threading',
        'time',
        'random',
        'json',
        'os',
        'sys',
        'device_license',
        'multiple_jobs_processor',
        'huid_data_processor',
        'request_generator',
        'mysql.connector',
        'mysql.connector.locales',
        'mysql.connector.locales.eng',
        'mysql.connector.plugins',
        'mysql.connector.plugins.mysql_native_password',
        'mysql.connector.plugins.caching_sha2_password',
        'mysql.connector.cursor',
        'mysql.connector.pooling',
        'mysql.connector.errors',
        'job_cards_processor',
        'delivery_voucher_processor',
        'weight_capture_processor',
    ],
    hookspath=['.'],  # Use hooks from current directory
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='manak_desktop_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # Disable UPX for better Windows 7 compatibility
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
